POST http://localhost:5001/api/auth/register
Content-Type: application/json

{
    "email": "thai@gmail.com",
    "password": "123",
    "confirmPassword": "123"
}

###
POST http://localhost:5001/api/auth/login
Content-Type: application/json

{
    "email": "son2@gmail.com",
    "password": "123"
}


###
GET http://localhost:3001/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjUyODUzMjNmNGIyZGZhMDU0NjUzM2MiLCJpYXQiOjE2NDk1NzUyMTgsImV4cCI6MTY0OTU3ODgxOH0.jeNeNZEbJqElw9qZo0FS8fpSv4BQdJ9mE4H6zylLdCU

###
POST http://localhost:3001/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjUyODUzMjNmNGIyZGZhMDU0NjUzM2MiLCJpYXQiOjE2NDk1NzUyMTgsImV4cCI6MTY0OTU3ODgxOH0.jeNeNZEbJqElw9qZo0FS8fpSv4BQdJ9mE4H6zylLdCU

{
    "content": " thai post 2"
}