POST http://localhost:5001/api/auth/register
Content-Type: application/json

{
    "email": "nhu@gmail.com",
    "password": "123",
    "confirmPassword": "123"
}

###
POST http://localhost:5001/api/auth/login
Content-Type: application/json

{
    "email": "nhu@gmail.com",
    "password": "123"
}


###
GET http://localhost:3001/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjU2Y2U2Y2MyMDdhNGU3MWZjNWVlYzQiLCJpYXQiOjE2NDk5ODQ1NDIsImV4cCI6MTY0OTk4ODE0Mn0.A7hTh74x6Y5q6Y-NdeDb1uHmCgj_HkZI00rR1GI1gIM
###
POST http://localhost:3001/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjU2Y2U2Y2MyMDdhNGU3MWZjNWVlYzQiLCJpYXQiOjE2NDk5ODQ5NDcsImV4cCI6MTY0OTk4ODU0N30.WPU32w3HHnnNTgHY04XFszxwLbKWHE8oDo_SxFqkiCI

{
    "content": " nhu post 3"
}

###
GET http://localhost:3001/api/comments/6252854a4c49cb901069a280
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjU2Y2U2Y2MyMDdhNGU3MWZjNWVlYzQiLCJpYXQiOjE2NTAxNzE5ODUsImV4cCI6MTY1MDE3NTU4NX0.wgyZgJYHx0ofrcRP5Ua0pbQmgO7wkd4zkz_4TuArh6Y

###
POST http://localhost:3001/api/comments/6252854a4c49cb901069a280/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjUyODUzMjNmNGIyZGZhMDU0NjUzM2MiLCJpYXQiOjE2NTAxNzIzNTcsImV4cCI6MTY1MDE3NTk1N30.qSDgDw_MFoFxeG9sNm80R7xhuyhShUflCL_rJDxoWa4

{
    "content": " thai comment 1"
}